name: 'Render Localized HTML'
description: 'WIP action for rendering localized HTML files'
branding:
  icon: globe
  color: blue
inputs:
  workspace:
    description: 'The workspace directory.'
    default: '/github/workspace'
  translation:
    description: 'The .json file to use for translation (relative to workspace). Example, "translations.json".'
    required: true
  input:
    description: 'The directory to localize from (relative to workspace). Example, "path/to/source".'
    required: true
  output:
    description: 'The directory to localize into (relative to workspace). Example, "path/to/destination".'
    required: true

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
  - '-w'
  - ${{ inputs.workspace }}
  - '-t'
  - ${{ inputs.translation }}
  - '-i'
  - ${{ inputs.input }}
  - '-o'
  - ${{ inputs.output }}
